// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetPlaylistById(arg1:string):Promise<models.Playlist>;

export function GetPlaylistItemByPlaylistId(arg1:string):Promise<Array<models.PlaylistItem>>;
