// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlaylistById(arg1) {
  return window['go']['handler']['Playlist']['GetPlaylistById'](arg1);
}

export function GetPlaylistItemByPlaylistId(arg1) {
  return window['go']['handler']['Playlist']['GetPlaylistItemByPlaylistId'](arg1);
}
